
spring:
  application:
    name: scw-project #应用名称
  datasource: #数据库连接参数
    # url: jdbc:mysql://192.168.146.3:3306/atcrowdfunding
    url: jdbc:mysql://47.116.5.173:3306/atcrowdfunding
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis: #redis的配置
    # host: 192.168.146.3
    host: 47.116.5.173
    port: 16379
    
#mybatis配置
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
    
#端口号
server:
  port: 8000
  
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.146.1     # 指定当前应用的ip地址